name: example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mtrust_sec_kit:
    path: ../
  mtrust_urp_types: ^6.0.0
  mtrust_urp_ble_strategy: ^9.0.0
  mtrust_urp_virtual_strategy: ^9.0.0
  mtrust_urp_ui: ^9.0.0
  liquid_flutter: ^19.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: packages/liquid_flutter/fonts/Lato-Regular.ttf
          weight: 500
        - asset: packages/liquid_flutter/fonts/Lato-Bold.ttf
          weight: 800
