name: mtrust_sec_kit
description: A comprehensive SDK for interfacing with the MTrust SEC Readers.
  Including an example to get you started as fast as possible.
version: 1.0.2-0
repository: https://github.com/emdgroup/mtrust-sec-kit
environment:
  sdk: ">=3.2.5 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  liquid_flutter: ^18.1.1
  mtrust_urp_core: ^9.0.0-0
  mtrust_urp_types: ^4.1.0
  mtrust_urp_ui: ^9.0.0-0
dependency_overrides:
  mtrust_urp_core:
    path: ../mtrust-urp/mtrust_urp_core
  mtrust_urp_ui:
    path: ../mtrust-urp/mtrust_urp_ui
dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  mtrust_urp_virtual_strategy: ^9.0.0-0
  very_good_analysis: ^5.1.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
